[package]
name = "Minesweeper"
version = "0.2.0"
authors = ["Ksawery Chodyniecki <ksawery.chodyniecki@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.5"
termion = "*"
